# Generated by Django 3.1.6 on 2021-03-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='refence',
            new_name='reference',
        ),
        migrations.AddField(
            model_name='table',
            name='area',
            field=models.CharField(choices=[('UP', 'Up Stair'), ('EXT', 'Exterior'), ('MAI', 'Main Room')], default='MAI', max_length=3),
        ),
    ]
