# Generated by Django 3.1.6 on 2021-04-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210329_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('at_lunch', models.BooleanField(default=True)),
                ('at_dinner', models.BooleanField(default=True)),
                ('state', models.CharField(choices=[('O', 'Opened'), ('C', 'Closed')], default='C', max_length=1, verbose_name='The restaurant is: ')),
            ],
        ),
        migrations.CreateModel(
            name='WeekDayOpened',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, unique=True)),
                ('is_opened_lunch', models.BooleanField(default=False)),
                ('is_opened_dinner', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='DateClosed',
        ),
    ]
