# Generated by Django 3.1.6 on 2021-04-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20210402_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datespecial',
            name='state',
            field=models.CharField(choices=[('O', 'Opened'), ('C', 'Closed')], default='C', max_length=1, verbose_name='The restaurant is'),
        ),
    ]
