# Generated by Django 3.1.6 on 2021-04-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210403_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datespecial',
            name='state',
            field=models.CharField(choices=[('Open', 'Opened'), ('Close', 'Closed')], default='C', max_length=5, verbose_name='The restaurant is'),
        ),
    ]
