# Generated by Django 3.1.6 on 2021-04-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20210405_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datespecial',
            name='state',
        ),
    ]
