# Generated by Django 3.1.6 on 2021-04-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_datespecial_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='form_type',
            field=models.CharField(choices=[('High', 'High'), ('Standard', 'Standard'), ('Low', 'Low')], max_length=10, verbose_name='Table height'),
        ),
    ]
