# Generated by Django 3.1.6 on 2021-04-09 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20210407_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tables',
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_table', to='booking.table'),
        ),
    ]
