# Generated by Django 3.1.6 on 2021-04-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20210409_1322'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('table', 'booking_date', 'booking_time'), name='unique_date_time_table'),
        ),
    ]
