# Generated by Django 3.1.6 on 2021-04-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20210409_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(max_length=21, unique=True),
        ),
    ]
