# Generated by Django 3.1.6 on 2021-04-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_booking_honored'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekdayopened',
            old_name='is_opened_dinner',
            new_name='at_dinner',
        ),
        migrations.RenameField(
            model_name='weekdayopened',
            old_name='is_opened_lunch',
            new_name='at_lunch',
        ),
    ]
