# Generated by Django 3.1.6 on 2021-04-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20210415_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.CharField(choices=[('lunch', 'lunch'), ('dinner', 'dinner')], default='lunch', max_length=6),
        ),
    ]
